version: '3'

services:
  db:
    image: postgres:14.0
    container_name: postgres
    environment:
      POSTGRES_DB: lol_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    restart: always

volumes:
  db-data: